#!/bin/bash

echo "Quick cleanup options for this repo:"
echo ""
echo "1. Delete test artifacts (save 170MB):"
echo "   rm -rf archive/"
echo ""
echo "2. Delete analysis reports (save 10MB):"
echo "   rm -f *_ANALYSIS.md *_REPORT.md *_RESULTS.md"
echo ""
echo "3. Delete dev folder (save 5MB but lose tests):"
echo "   rm -rf dev/"
echo ""
echo "4. Nuclear option - keep only what matters:"
echo "   mkdir ../interview_prep_clean"
echo "   cp index.html src/ ../interview_prep_clean/"
echo "   # Use the clean folder instead"
echo ""
echo "5. Or just use it as-is because it works!"