#!/bin/bash

echo "📦 Git Repository Setup Instructions"
echo "===================================="
echo ""
echo "Your local git repository is ready! To push to GitHub:"
echo ""
echo "1. Create a new repository on GitHub:"
echo "   - Go to https://github.com/new"
echo "   - Name: turing-interview-prep (or your choice)"
echo "   - Description: 'Comprehensive interview guide for Turing DevOps Engineer position'"
echo "   - Keep it private if it contains personal info"
echo "   - Don't initialize with README (we already have one)"
echo ""
echo "2. Add the remote and push:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/turing-interview-prep.git"
echo "   git push -u origin main"
echo ""
echo "3. Optional: Create GitHub Pages for the guide:"
echo "   - Go to Settings → Pages"
echo "   - Source: Deploy from branch"
echo "   - Branch: main"
echo "   - Folder: /dist"
echo "   - Your guide will be live at: https://YOUR_USERNAME.github.io/turing-interview-prep/"
echo ""
echo "📁 Current repository status:"
git status --short
echo ""
echo "📊 Repository stats:"
echo "Files: $(git ls-files | wc -l)"
echo "Size: $(du -sh . | cut -f1)"
echo "Commits: $(git rev-list --all --count)"